package com.marsx.pool;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;

public final class FinanceActivity extends Activity{
 LinearLayout root; TextView result,status,brokerStatus,marketPrice,marketProviders; ChartView chartView; EditText amount; Spinner from,to,fromNet,toNet; int ACCENT=Color.rgb(255,106,0),BG=Color.rgb(4,7,12),CARD=Color.rgb(10,14,22),RAISED=Color.rgb(15,20,31),MUTED=Color.rgb(158,169,188); final int[] THEMES={Color.rgb(255,106,0),Color.rgb(185,60,255),Color.rgb(0,216,255),Color.rgb(80,145,255),Color.rgb(230,55,70)}; int themeIndex=0;
 @Override public void onCreate(Bundle b){super.onCreate(b);themeIndex=getPreferences(MODE_PRIVATE).getInt("theme",0);if(themeIndex<0||themeIndex>=THEMES.length)themeIndex=0;ACCENT=THEMES[themeIndex];build();}
 void build(){if(root!=null)root=null;ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,24,28,34);root.setBackgroundColor(BG);
  rowTitle(); balanceCard(); cardHeader(); selectors(); quoteInfo(); popularPairs(); marketCard(); brokerCard(); nav(); s.addView(root);setContentView(s); health(); brokerHealth(); marketProviders(); chartSnapshot();
 }
 void rowTitle(){LinearLayout r=row();LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);TextView logo=t("MARS-X",26,Color.WHITE);logo.setTypeface(null,Typeface.BOLD);logo.setLetterSpacing(.04f);oneLine(logo);brand.addView(logo);TextView sub=t("Dönüştür",13,ACCENT);sub.setTypeface(null,Typeface.BOLD);sub.setLetterSpacing(.08f);oneLine(sub);brand.addView(sub);r.addView(brand,new LinearLayout.LayoutParams(0,-2,1));status=t("● Bağlanıyor",12,MUTED);oneLine(status);status.setBackground(pill(Color.rgb(16,20,30),ACCENT));status.setPadding(14,10,14,10);r.addView(status);root.addView(r);}
 void balanceCard(){LinearLayout c=card();c.setBackground(panel(RAISED,22,Color.rgb(37,48,66)));TextView h=t("MEVCUT BAKİYE",11,MUTED);h.setLetterSpacing(.08f);c.addView(h);TextView v=t("—",34,Color.WHITE);v.setTypeface(null,Typeface.BOLD);c.addView(v);c.addView(t("Önizleme modu • gerçek bakiye üretilmez",12,MUTED));root.addView(c,mp(12));}
 void themePicker(){LinearLayout r=row();String[] n={"Mars","Fin","Aqua","Ocean","Red"};for(int i=0;i<n.length;i++){final int k=i;Button b=new Button(this);b.setText(n[i]);b.setTextSize(10);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setMinWidth(0);b.setPadding(2,0,2,0);b.setBackground(pill(k==themeIndex?THEMES[i]:Color.rgb(14,18,28),THEMES[i]));b.setOnClickListener(v->{themeIndex=k;ACCENT=THEMES[k];getPreferences(MODE_PRIVATE).edit().putInt("theme",k).apply();build();});r.addView(b,new LinearLayout.LayoutParams(0,46,1));}root.addView(r,mp(10));}
 void metricCard(LinearLayout r,String label,String value,String note){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(16,14,16,14);c.setBackground(round(Color.rgb(10,14,24),18));TextView l=t(label,10,MUTED);l.setLetterSpacing(.06f);c.addView(l);TextView val=t(value,20,Color.WHITE);val.setTypeface(null,Typeface.BOLD);c.addView(val);c.addView(t(note,10,MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(4,0,4,0);r.addView(c,p);}
 void cardHeader(){LinearLayout c=card();c.setBackground(panel(CARD,22,ACCENT));TextView h=t("KRİPTO DÖNÜŞTÜR",13,ACCENT);h.setLetterSpacing(.10f);h.setTypeface(null,Typeface.BOLD);c.addView(h);c.addView(t("Hızlı, güvenli ve en iyi oran önizlemesi",12,MUTED));root.addView(c,mp(14));}
 void selectors(){LinearLayout c=(LinearLayout)root.getChildAt(root.getChildCount()-1);String[] assets={"BTC · Bitcoin","ETH · Ethereum","USDT · Tether","SOL · Solana","BNB · BNB","DOGE · Dogecoin"};c.addView(label("Gönderilecek Coin"));from=spin(assets,0);c.addView(from);c.addView(label("Dönüştürülecek Miktar"));amount=new EditText(this);amount.setText("0.01");amount.setTextColor(Color.WHITE);amount.setTextSize(29);amount.setTypeface(null,Typeface.BOLD);amount.setInputType(2|8192);amount.setBackground(box());amount.setPadding(22,20,22,20);c.addView(amount,mp(6));c.addView(label("Ağ Seçimi"));fromNet=spin(new String[]{"Bitcoin (BTC)","Ethereum (ERC20)","Solana","BNB Smart Chain"},0);c.addView(fromNet);TextView swap=t("⇅",34,ACCENT);swap.setGravity(Gravity.CENTER);swap.setTypeface(null,Typeface.BOLD);c.addView(swap);c.addView(label("Alınacak Coin"));to=spin(assets,1);c.addView(to);c.addView(label("Ağ Seçimi"));toNet=spin(new String[]{"Ethereum (ERC20)","Bitcoin (BTC)","Solana","BNB Smart Chain"},0);c.addView(toNet);
  LinearLayout stats=row();metricCard(stats,"Piyasa Oranı","—","provider quote");metricCard(stats,"Ağ Ücreti","—","estimate");c.addView(stats,mp(12));LinearLayout stats2=row();metricCard(stats2,"Min. Tutar","—","route gate");metricCard(stats2,"Geçerlilik","10 dk","preview");c.addView(stats2,mp(8));
  Button q=new Button(this);q.setText("Dönüştür");q.setTextSize(18);q.setTypeface(null,Typeface.BOLD);q.setTextColor(Color.BLACK);q.setBackground(round(ACCENT,18));q.setOnClickListener(v->quote());c.addView(q,mp(16));result=t("Bu ekran önizleme modundadır. Gerçek işlem oluşturulmaz.",14,Color.LTGRAY);c.addView(result);
 }
 void quoteInfo(){LinearLayout c=card();c.addView(t("Hizmet Durumu",12,ACCENT));c.addView(t("ChangeNOW read-only quote • Broker kapıları kilitli • KYC/SCA olmadan gerçek işlem yok",12,MUTED));String[] f={"✓ Hizlı işlem","✓ En iyi oranlar","✓ Çoklu ağ","✓ Varlıklar güvende","✓ Kayıt gerektirmez","✓ İşlem kapalı"};for(int i=0;i<3;i++){LinearLayout r=row();feature(r,f[i*2]);feature(r,f[i*2+1]);c.addView(r,mp(4));}root.addView(c,mp(12));}
 void popularPairs(){LinearLayout c=card();c.addView(t("POPÜLER ÇİFTLER",12,ACCENT));String[] pairs={"BTC  ›  ETH","ETH  ›  USDT","BNB  ›  USDT","SOL  ›  USDT","USDT  ›  TRX"};for(String pair:pairs){TextView p=t(pair+"        veri bekleniyor",14,Color.WHITE);p.setBackground(pill(Color.rgb(12,17,27),Color.rgb(35,45,62)));p.setPadding(16,10,16,10);c.addView(p,mp(6));}root.addView(c,mp(12));}
 void brokerCard(){LinearLayout c=card();c.addView(t("SİSTEM DURUMU",12,ACCENT));brokerStatus=t("Broker durumu kontrol ediliyor…",13,MUTED);c.addView(brokerStatus);c.addView(t("İşlem modu: Önizleme • canlı emir ve çekim kapalı",12,MUTED));root.addView(c,mp(12));}
 void marketCard(){LinearLayout c=card();c.addView(t("PİYASA ÖZETİ",12,ACCENT));marketPrice=t("BTC / USD     —     veri bekleniyor",18,Color.WHITE);marketPrice.setTypeface(null,Typeface.BOLD);oneLine(marketPrice);c.addView(marketPrice);TextView tf=t("1m  5m  15m  1h  4h  1D",12,MUTED);tf.setGravity(Gravity.CENTER);oneLine(tf);c.addView(tf);chartView=new ChartView(this);chartView.accent=ACCENT;chartView.setContentDescription("BTC USD mum grafiği; veri bekleniyor");c.addView(chartView,new LinearLayout.LayoutParams(-1,240));c.addView(t("Mum grafik • hacim • salt okunur veri",12,MUTED));marketProviders=t("Piyasa verisi: Coinbase + Kraken + Bybit hazırlanıyor",12,MUTED);c.addView(marketProviders);root.addView(c,mp(12));}
 void nav(){LinearLayout r=row();String[] items={"Ana Sayfa","Piyasalar","Trading","Portföy","Cüzdan","Profil"};for(String item:items){TextView n=t(item,10,MUTED);n.setGravity(Gravity.CENTER);oneLine(n);n.setBackground(pill(Color.rgb(8,11,18),item.equals("Trading")?ACCENT:Color.rgb(32,40,56)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,52,1);p.setMargins(2,0,2,0);r.addView(n,p);n.setOnClickListener(v->openFinanceScreen(item));}root.addView(r,mp(20));}
 void openFinanceScreen(String name){
  if("Trading".equals(name)){new AlertDialog.Builder(this).setTitle("MARS-X Trading").setMessage("Profesyonel grafik ve salt okunur piyasa bilgileri ana terminalde gösterilir. Canlı emirler kapalıdır.").setPositiveButton("Tamam",null).show();return;}
  final int white=Color.WHITE;ScrollView scroll=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(26,24,26,26);body.setBackgroundColor(BG);scroll.addView(body);
  TextView heading=t(name.toUpperCase(Locale.ROOT),24,white);heading.setTypeface(null,Typeface.BOLD);heading.setLetterSpacing(.06f);body.addView(heading);body.addView(t("MARS-X FINANCE  /  DEMO WORKSPACE",10,ACCENT));
  if("Ana Sayfa".equals(name)){financeHero(body,"TOPLAM PORTFÖY","—","Canlı bakiye bağlantısı bekleniyor");financeSection(body,"PİYASA GENEL BAKIŞ");financeLine(body,"BTC / USD","Veri bekleniyor");financeLine(body,"ETH / USD","Veri bekleniyor");financeLine(body,"SOL / USD","Veri bekleniyor");financeSection(body,"HIZLI İŞLEMLER");financeAction(body,"Piyasaları Gör",()->openFinanceScreen("Piyasalar"));financeAction(body,"Cüzdanı Aç",()->openFinanceScreen("Cüzdan"));}
  else if("Piyasalar".equals(name)){financeSection(body,"İZLEME LİSTESİ");for(String coin:new String[]{"BTC / USD","ETH / USD","SOL / USD","BNB / USD","EUR / USD","XAU / USD"})financeLine(body,coin,"—");financeSection(body,"VERİ KALİTESİ");financeLine(body,"Durum","Bağlantı bekleniyor");financeLine(body,"Veri kaynağı","Salt okunur");}
  else if("Portföy".equals(name)){financeHero(body,"PORTFÖY DEĞERİ","—","Doğrulanmış bakiye bulunmuyor");financeSection(body,"VARLIK DAĞILIMI");financeLine(body,"Spot Varlıklar","—");financeLine(body,"Açık Pozisyonlar","—");financeLine(body,"Günlük Kâr / Zarar","—");financeSection(body,"PERFORMANS");financeLine(body,"Gerçekleşmiş Kâr / Zarar","—");financeLine(body,"Geçmiş İşlemler","Henüz veri yok");}
  else if("Cüzdan".equals(name)){financeHero(body,"CÜZDAN BAKİYESİ","—","Bakiye sağlayıcısı bağlı değil");financeSection(body,"CÜZDAN İŞLEMLERİ");financeAction(body,"Para Yatır",()->financePreview("Para yatırma"));financeAction(body,"Para Çek",()->financePreview("Para çekme"));financeAction(body,"Transfer",()->financePreview("Transfer"));financeSection(body,"VARLIKLAR");for(String coin:new String[]{"BTC","ETH","USDT","SOL"})financeLine(body,coin,"—");}
  else if("Profil".equals(name)){financeSection(body,"HESAP");financeLine(body,"Oturum","Demo");financeLine(body,"Kimlik Doğrulama","Bağlı değil");financeSection(body,"GÜVENLİK");financeLine(body,"İki Aşamalı Doğrulama","Yapılandırılmadı");financeLine(body,"Cihazlar","—");financeSection(body,"TERCİHLER");financeAction(body,"Görünüm ve Tema",()->financePreview("Tema"));financeAction(body,"Bildirimler",()->financePreview("Bildirimler"));financeAction(body,"İşlem Geçmişi",()->financePreview("İşlem geçmişi"));financeAction(body,"Fiyat Alarmları",()->financePreview("Fiyat alarmları"));}
  new AlertDialog.Builder(this).setView(scroll).setPositiveButton("Kapat",null).show();
 }
 void financeHero(LinearLayout parent,String label,String value,String note){LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(24,22,24,22);panel.setBackground(panel(RAISED,22,ACCENT));TextView title=t(label,11,ACCENT);title.setLetterSpacing(.08f);panel.addView(title);TextView big=t(value,35,Color.WHITE);big.setTypeface(null,Typeface.BOLD);panel.addView(big);panel.addView(t(note,12,MUTED));parent.addView(panel,mp(20));}
 void financeSection(LinearLayout parent,String title){TextView v=t(title,12,ACCENT);v.setTypeface(null,Typeface.BOLD);v.setLetterSpacing(.08f);parent.addView(v,mp(24));}
 void financeAction(LinearLayout parent,String title,Runnable action){Button b=new Button(this);b.setText(title+"   →");b.setTextSize(14);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setGravity(Gravity.CENTER_VERTICAL|Gravity.LEFT);b.setPadding(24,12,16,12);b.setBackground(panel(RAISED,16,Color.rgb(37,48,66)));b.setOnClickListener(v->action.run());parent.addView(b,mp(8));}
 void financePreview(String title){new AlertDialog.Builder(this).setTitle(title).setMessage("MARS-X Finance arayüz önizlemesi. Gerçek işlem veya hesap değişikliği yapılmaz.").setPositiveButton("Tamam",null).show();}
 void financeLine(LinearLayout parent,String key,String value){LinearLayout r=row();r.setPadding(18,18,18,18);r.setBackground(panel(RAISED,14,Color.rgb(37,48,66)));TextView left=t(key,14,Color.WHITE);r.addView(left,new LinearLayout.LayoutParams(0,-2,1));r.addView(t(value,12,MUTED));parent.addView(r,mp(7));}
 void health(){new Thread(()->{try{JSONObject j=get("/convert/health");boolean ok=j.optBoolean("configured",false);runOnUiThread(()->{status.setText(ok?"● Fiyat API hazır":"● Bağlantı Bekleniyor");status.setTextColor(ok?Color.rgb(0,220,160):Color.LTGRAY);});}catch(Exception e){runOnUiThread(()->status.setText("● Hizmet Bekleniyor"));}}).start();}
 void brokerHealth(){new Thread(()->{try{JSONObject j=get("/broker/health");JSONArray p=j.optJSONArray("providers");JSONObject b=p==null||p.length()==0?null:p.optJSONObject(0);boolean configured=b!=null&&b.optBoolean("configured",false);JSONObject prod=j.optJSONObject("production");boolean trading=prod!=null&&prod.optBoolean("liveTrading",false);String text=(configured?"lemon bağlantısı hazır":"lemon API anahtarı bekleniyor")+" • "+(trading?"production review hazır":"güvenlik kapıları kilitli");runOnUiThread(()->{brokerStatus.setText(text);brokerStatus.setTextColor(trading?Color.rgb(0,220,160):(configured?Color.rgb(255,190,90):Color.LTGRAY));});}catch(Exception e){runOnUiThread(()->brokerStatus.setText("Broker durumu alınamadı. Paper mod korunuyor."));}}).start();}
 void marketProviders(){new Thread(()->{try{JSONObject j=get("/market/providers");JSONArray p=j.optJSONArray("providers");ArrayList<String> ready=new ArrayList<>();if(p!=null)for(int i=0;i<p.length();i++){JSONObject x=p.optJSONObject(i);if(x!=null&&"DATA_READY".equals(x.optString("status")))ready.add(x.optString("id"));}String text=ready.isEmpty()?"Data agents bekleniyor":"Data agents: "+String.join(" + ",ready)+" • read-only";runOnUiThread(()->marketProviders.setText(text));}catch(Exception e){runOnUiThread(()->marketProviders.setText("Data agents alınamadı • read-only mod korunuyor"));}}).start();}
 void chartSnapshot(){new Thread(()->{try{
   JSONObject j=get("/chart/snapshot?symbol=BTC-USD&timeframe=1m");
   JSONArray candles=j.getJSONObject("series").getJSONArray("candles");
   if(candles.length()==0)throw new IOException("No market candles");
   JSONObject last=candles.getJSONObject(candles.length()-1);
   double close=last.optDouble("close",Double.NaN);
   if(!Double.isFinite(close)||close<=0)throw new IOException("Invalid close price");
   String text="BTC / USD     "+String.format(Locale.ROOT,"%,.2f",close)+"     READ-ONLY";
   runOnUiThread(()->{chartView.setCandles(candles);marketPrice.setText(chartView.candles.isEmpty()?"BTC / USD     veri bekleniyor     READ-ONLY":text);});
  }catch(Exception e){runOnUiThread(()->{marketPrice.setText("BTC / USD     veri bekleniyor     READ-ONLY");chartView.clear();});}}).start();}
 void quote(){String f=asset(from),tt=asset(to),a=amount.getText().toString().trim();if(!a.matches("[0-9]+(\\.[0-9]{1,12})?")){result.setText("Geçerli bir miktar gir.");return;}result.setText("Fiyat hesaplanıyor…");new Thread(()->{try{String path="/convert/quote?fromCurrency="+enc(f)+"&toCurrency="+enc(tt)+"&fromAmount="+enc(a);JSONObject j=get(path);JSONObject d=j.optJSONObject("data");String out=d==null?"Fiyat şu anda alınamadı.":("Tahmini alacağın miktar\n"+d.optString("toAmount",d.optString("estimatedAmount","—"))+" "+tt.toUpperCase(Locale.ROOT)+"\nİşlem oluşturulmadı.");runOnUiThread(()->result.setText(out));}catch(Exception e){runOnUiThread(()->result.setText("Fiyat servisi şu anda kullanılamıyor. İşlem oluşturulmadı."));}}).start();}
 JSONObject get(String p)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(BuildConfig.MARSX_FINANCE_API_BASE_URL+p).openConnection();c.setConnectTimeout(7000);c.setReadTimeout(7000);c.setRequestProperty("Accept","application/json");int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();String body=read(in);c.disconnect();if(code>=400)throw new IOException("HTTP "+code);return new JSONObject(body);}
 String read(InputStream in)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String l;while((l=r.readLine())!=null&&b.length()<8192)b.append(l);return b.toString();}
 String enc(String s)throws Exception{return URLEncoder.encode(s,"UTF-8");}String asset(Spinner s){return s.getSelectedItem().toString().split(" ")[0].toLowerCase(Locale.ROOT);}
 Spinner spin(String[] a,int i){Spinner s=new Spinner(this);ArrayAdapter<String>d=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a){public View getView(int p,View v,android.view.ViewGroup g){TextView x=(TextView)super.getView(p,v,g);x.setTextColor(Color.WHITE);x.setTextSize(17);x.setPadding(18,18,18,18);x.setBackgroundColor(CARD);return x;}};s.setAdapter(d);s.setSelection(i);return s;}
 TextView label(String x){TextView v=t(x,12,MUTED);v.setLetterSpacing(.05f);return v;}
 void feature(LinearLayout r,String x){TextView v=t(x,12,Color.WHITE);v.setBackground(pill(Color.rgb(12,17,27),Color.rgb(38,49,68)));v.setPadding(12,8,12,8);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(3,0,3,0);r.addView(v,p);}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(22,20,22,22);c.setBackground(round(CARD,22));return c;}LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
 TextView t(String x,int z,int col){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);v.setTextColor(col);v.setPadding(0,8,0,8);return v;}void oneLine(TextView v){v.setSingleLine(true);v.setEllipsize(android.text.TextUtils.TruncateAt.END);}void title(String x,int z){TextView v=t(x,z,Color.WHITE);v.setTypeface(null,Typeface.BOLD);root.addView(v);}void muted(String x){root.addView(t(x,14,MUTED));}
 LinearLayout.LayoutParams mp(int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=top;return p;}GradientDrawable round(int col,int rad){GradientDrawable g=new GradientDrawable();g.setColor(col);g.setCornerRadius(rad);return g;}GradientDrawable pill(int col,int stroke){GradientDrawable g=round(col,999);g.setStroke(1,stroke);return g;}GradientDrawable panel(int col,int rad,int stroke){GradientDrawable g=round(col,rad);g.setStroke(2,stroke);return g;}GradientDrawable box(){GradientDrawable g=round(Color.rgb(16,23,34),16);g.setStroke(1,Color.rgb(56,32,82));return g;}
 static final class ChartView extends View{
  Paint p=new Paint(1);ArrayList<float[]> candles=new ArrayList<>();int accent=Color.rgb(255,112,0);
  ChartView(android.content.Context c){super(c);setBackgroundColor(Color.rgb(7,12,19));}
  void clear(){candles.clear();setContentDescription("BTC USD mum grafiği; veri bekleniyor");invalidate();}
  void setCandles(JSONArray a){
   ArrayList<float[]> verified=new ArrayList<>();
   try{
    int start=Math.max(0,a.length()-64);
    for(int i=start;i<a.length();i++){
     JSONObject x=a.getJSONObject(i);
     double o=x.optDouble("open",Double.NaN),hi=x.optDouble("high",Double.NaN),lo=x.optDouble("low",Double.NaN),cl=x.optDouble("close",Double.NaN),v=x.optDouble("volume",0);
     if(!Double.isFinite(o)||!Double.isFinite(hi)||!Double.isFinite(lo)||!Double.isFinite(cl)||!Double.isFinite(v)
       ||o<=0||cl<=0||hi<Math.max(o,cl)||lo>Math.min(o,cl)||lo<=0||v<0)continue;
     verified.add(new float[]{(float)o,(float)hi,(float)lo,(float)cl,(float)v});
    }
   }catch(Exception ignored){verified.clear();}
   candles.clear();candles.addAll(verified);
   setContentDescription(candles.isEmpty()?"BTC USD mum grafiği; veri bekleniyor":"BTC USD doğrulanmış mum grafiği; salt okunur");
   invalidate();
  }
  protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight(),top=18,chartH=(int)(h*.72),volTop=top+chartH+18,volH=h-volTop-18;p.setStrokeWidth(1);p.setColor(Color.rgb(30,40,50));for(int i=0;i<=4;i++)c.drawLine(0,top+chartH*i/4f,w,top+chartH*i/4f,p);if(candles.isEmpty()){p.setStyle(Paint.Style.FILL);p.setColor(Color.LTGRAY);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(30);c.drawText("VERİ BEKLENİYOR",w/2f,h/2f,p);p.setTextSize(20);c.drawText("Gerçek piyasa verisi bulunamadı",w/2f,h/2f+38,p);p.setTextAlign(Paint.Align.LEFT);return;}float hi=0,lo=Float.MAX_VALUE,mv=1;for(float[] x:candles){hi=Math.max(hi,x[1]);lo=Math.min(lo,x[2]);mv=Math.max(mv,x[4]);}float gap=Math.max(6,w/(float)Math.max(24,candles.size())),body=Math.max(3,gap*.55f);Path sma=new Path();for(int i=0;i<candles.size();i++){float[] x=candles.get(i);float cx=i*gap+gap*.7f,yo=y(x[0],hi,lo,top,chartH),yh=y(x[1],hi,lo,top,chartH),yl=y(x[2],hi,lo,top,chartH),yc=y(x[3],hi,lo,top,chartH);boolean up=x[3]>=x[0];p.setColor(up?Color.rgb(22,199,132):Color.rgb(234,57,67));p.setStrokeWidth(2);c.drawLine(cx,yh,cx,yl,p);p.setStyle(Paint.Style.FILL);c.drawRoundRect(cx-body/2,Math.min(yo,yc),cx+body/2,Math.max(yo,yc)+1,3,3,p);p.setColor(Color.argb(130,180,190,205));c.drawRect(cx-body/2,volTop+volH*(1-x[4]/mv),cx+body/2,volTop+volH,p);if(i>=7){float s=0;for(int k=i-7;k<=i;k++)s+=candles.get(k)[3];float sy=y(s/8,hi,lo,top,chartH);if(i==7)sma.moveTo(cx,sy);else sma.lineTo(cx,sy);}}p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(accent);c.drawPath(sma,p);p.setStyle(Paint.Style.FILL);p.setTextSize(24);p.setColor(Color.LTGRAY);c.drawText("SMA 8",18,chartH+top-14,p);c.drawText("VOL",18,h-18,p);}
  float y(float v,float hi,float lo,int top,int chartH){return top+(hi-v)/Math.max(1,hi-lo)*chartH;}
 }
}
