package com.marsx.pool;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;

public final class FinanceActivity extends Activity{
 LinearLayout root; TextView result,status,brokerStatus,marketPrice,marketProviders; ChartView chartView; EditText amount; Spinner from,to,fromNet,toNet; int ACCENT=Color.rgb(185,60,255),BG=Color.rgb(5,7,13),CARD=Color.rgb(13,17,26),RAISED=Color.rgb(18,24,39),MUTED=Color.rgb(169,179,198); final int[] THEMES={Color.rgb(185,60,255),Color.rgb(255,106,0),Color.rgb(0,216,255),Color.rgb(80,145,255),Color.rgb(230,55,70)}; int themeIndex=0;
 @Override public void onCreate(Bundle b){super.onCreate(b);themeIndex=getPreferences(MODE_PRIVATE).getInt("theme",0);if(themeIndex<0||themeIndex>=THEMES.length)themeIndex=0;ACCENT=THEMES[themeIndex];build();}
 void build(){if(root!=null)root=null;ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,24,28,34);root.setBackgroundColor(BG);
  rowTitle(); themePicker(); financeHero(); quickActions();
  cardHeader(); selectors(); quoteInfo(); brokerCard(); marketCard(); nav(); s.addView(root);setContentView(s); health(); brokerHealth(); marketProviders(); chartSnapshot();
 }
 void rowTitle(){LinearLayout r=row();LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);TextView logo=t("MARS-X FINANCE",24,Color.WHITE);logo.setTypeface(null,Typeface.BOLD);logo.setLetterSpacing(.03f);oneLine(logo);brand.addView(logo);TextView sub=t("Financial Hub  •  READ-ONLY",11,MUTED);sub.setLetterSpacing(.08f);oneLine(sub);brand.addView(sub);r.addView(brand,new LinearLayout.LayoutParams(0,-2,1));status=t("● Bağlanıyor",12,MUTED);oneLine(status);status.setBackground(pill(Color.rgb(16,22,34),ACCENT));status.setPadding(14,10,14,10);r.addView(status);root.addView(r);}
 void themePicker(){LinearLayout r=row();String[] n={"Fin","Mars","Aqua","Ocean","Red"};for(int i=0;i<n.length;i++){final int k=i;Button b=new Button(this);b.setText(n[i]);b.setTextSize(10);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setMinWidth(0);b.setPadding(2,0,2,0);b.setBackground(pill(k==themeIndex?THEMES[i]:Color.rgb(17,22,34),THEMES[i]));b.setOnClickListener(v->{themeIndex=k;ACCENT=THEMES[k];getPreferences(MODE_PRIVATE).edit().putInt("theme",k).apply();build();});r.addView(b,new LinearLayout.LayoutParams(0,52,1));}root.addView(r,mp(12));}
 void financeHero(){LinearLayout c=card();c.setBackground(panel(RAISED,28,ACCENT));TextView h=t("TOTAL PORTFOLIO",12,ACCENT);h.setLetterSpacing(.10f);h.setTypeface(null,Typeface.BOLD);c.addView(h);TextView v=t("— EUR",38,Color.WHITE);v.setTypeface(null,Typeface.BOLD);oneLine(v);c.addView(v);c.addView(t("○  Portföy verisi bekleniyor  •  gerçek bakiye üretilmez",12,MUTED));LinearLayout row=row();metricCard(row,"24h P/L","—","read-only");metricCard(row,"Risk","Kilitli","execution off");c.addView(row,mp(10));root.addView(c,mp(18));}
 void quickActions(){String[] a={"Assets","Analytics","Reports","AI"};for(int rowIndex=0;rowIndex<2;rowIndex++){LinearLayout r=row();for(int i=rowIndex*2;i<rowIndex*2+2;i++){TextView chip=t(a[i],12,Color.WHITE);chip.setGravity(Gravity.CENTER);chip.setBackground(pill(Color.rgb(13,17,26),Color.rgb(36,46,66)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,54,1);p.setMargins(4,0,4,0);r.addView(chip,p);}root.addView(r,mp(rowIndex==0?10:8));}}
 void metricCard(LinearLayout r,String label,String value,String note){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(16,14,16,14);c.setBackground(round(Color.rgb(10,14,24),18));TextView l=t(label,10,MUTED);l.setLetterSpacing(.06f);c.addView(l);TextView val=t(value,20,Color.WHITE);val.setTypeface(null,Typeface.BOLD);c.addView(val);c.addView(t(note,10,MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(4,0,4,0);r.addView(c,p);}
 void cardHeader(){LinearLayout c=card();TextView h=t("CONVERT PREVIEW",12,ACCENT);h.setLetterSpacing(.09f);h.setTypeface(null,Typeface.BOLD);c.addView(h);c.addView(t("Provider-neutral quote preview. Execution is locked.",12,MUTED));root.addView(c,mp(14));}
 void selectors(){LinearLayout c=(LinearLayout)root.getChildAt(root.getChildCount()-1);String[] assets={"BTC · Bitcoin","ETH · Ethereum","USDT · Tether","SOL · Solana","BNB · BNB","DOGE · Dogecoin"};from=spin(assets,0);to=spin(assets,1);c.addView(from);amount=new EditText(this);amount.setText("0.01");amount.setTextColor(Color.WHITE);amount.setTextSize(25);amount.setInputType(2|8192);amount.setBackground(box());amount.setPadding(22,20,22,20);c.addView(amount,mp(12));c.addView(t("Ağ",12,Color.GRAY));fromNet=spin(new String[]{"Bitcoin (BTC)","Ethereum (ERC20)","Solana","BNB Smart Chain"},0);c.addView(fromNet);TextView swap=t("⇅",30,ACCENT);swap.setGravity(Gravity.CENTER);c.addView(swap);c.addView(t("Al",12,Color.GRAY));c.addView(to);c.addView(t("Ağ",12,Color.GRAY));toNet=spin(new String[]{"Ethereum (ERC20)","Bitcoin (BTC)","Solana","BNB Smart Chain"},0);c.addView(toNet);
  Button q=new Button(this);q.setText("Önizleme Al");q.setTextSize(17);q.setTextColor(Color.BLACK);q.setBackground(round(ACCENT,18));q.setOnClickListener(v->quote());c.addView(q,mp(18));result=t("Henüz fiyat önizlemesi alınmadı.",15,Color.LTGRAY);c.addView(result);
 }
 void quoteInfo(){LinearLayout c=card();c.addView(t("Rate     •     Min amount     •     Network fee",13,MUTED));c.addView(t("Gerçek işlem kapalıdır. Değerler yalnızca okunabilir fiyat önizlemesidir.",12,MUTED));root.addView(c,mp(12));}
 void brokerCard(){LinearLayout c=card();c.addView(t("BROKER GATEWAY",12,ACCENT));TextView h=t("lemon.markets review line",19,Color.WHITE);h.setTypeface(null,Typeface.BOLD);c.addView(h);brokerStatus=t("Broker durumu kontrol ediliyor…",14,MUTED);c.addView(brokerStatus);c.addView(t("Onboarding, KYC/SCA ve kullanıcı onayı tamamlanmadan gerçek emir veya çekim gönderilmez.",12,MUTED));root.addView(c,mp(12));}
 void marketCard(){LinearLayout c=card();c.addView(t("MARKETS",12,ACCENT));marketPrice=t("BTC / USD     —     chart loading",20,Color.WHITE);marketPrice.setTypeface(null,Typeface.BOLD);oneLine(marketPrice);c.addView(marketPrice);TextView tf=t("1m  5m  15m  1h  4h  1D  1W",13,MUTED);tf.setGravity(Gravity.CENTER);oneLine(tf);c.addView(tf);chartView=new ChartView(this);chartView.accent=ACCENT;chartView.setContentDescription("BTC USD mum grafiği; veri bekleniyor");c.addView(chartView,new LinearLayout.LayoutParams(-1,360));c.addView(t("Candles • volume • SMA 8 when verified data exists • execution locked",13,MUTED));marketProviders=t("Data agents: Coinbase + Kraken + Bybit hazırlanıyor",13,MUTED);c.addView(marketProviders);c.addView(t("BTC     ETH     BNB     SOL     DOGE",14,MUTED));root.addView(c,mp(12));}
 void nav(){LinearLayout r=row();String[] items={"Overview","Portfolio","Markets","More"};for(String item:items){TextView n=t(item,11,MUTED);n.setGravity(Gravity.CENTER);oneLine(n);n.setBackground(pill(Color.rgb(8,11,18),Color.rgb(32,40,56)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,52,1);p.setMargins(3,0,3,0);r.addView(n,p);}root.addView(r,mp(20));}
 void health(){new Thread(()->{try{JSONObject j=get("/convert/health");boolean ok=j.optBoolean("configured",false);runOnUiThread(()->{status.setText(ok?"● Fiyat API hazır":"● Bağlantı Bekleniyor");status.setTextColor(ok?Color.rgb(0,220,160):Color.LTGRAY);});}catch(Exception e){runOnUiThread(()->status.setText("● Hizmet Bekleniyor"));}}).start();}
 void brokerHealth(){new Thread(()->{try{JSONObject j=get("/broker/health");JSONArray p=j.optJSONArray("providers");JSONObject b=p==null||p.length()==0?null:p.optJSONObject(0);boolean configured=b!=null&&b.optBoolean("configured",false);JSONObject prod=j.optJSONObject("production");boolean trading=prod!=null&&prod.optBoolean("liveTrading",false);String text=(configured?"lemon bağlantısı hazır":"lemon API anahtarı bekleniyor")+" • "+(trading?"production review hazır":"güvenlik kapıları kilitli");runOnUiThread(()->{brokerStatus.setText(text);brokerStatus.setTextColor(trading?Color.rgb(0,220,160):(configured?Color.rgb(255,190,90):Color.LTGRAY));});}catch(Exception e){runOnUiThread(()->brokerStatus.setText("Broker durumu alınamadı. Paper mod korunuyor."));}}).start();}
 void marketProviders(){new Thread(()->{try{JSONObject j=get("/market/providers");JSONArray p=j.optJSONArray("providers");ArrayList<String> ready=new ArrayList<>();if(p!=null)for(int i=0;i<p.length();i++){JSONObject x=p.optJSONObject(i);if(x!=null&&"DATA_READY".equals(x.optString("status")))ready.add(x.optString("id"));}String text=ready.isEmpty()?"Data agents bekleniyor":"Data agents: "+String.join(" + ",ready)+" • read-only";runOnUiThread(()->marketProviders.setText(text));}catch(Exception e){runOnUiThread(()->marketProviders.setText("Data agents alınamadı • read-only mod korunuyor"));}}).start();}
 void chartSnapshot(){new Thread(()->{try{
   JSONObject j=get("/chart/snapshot?symbol=BTC-USD&timeframe=1m");
   JSONArray candles=j.getJSONObject("series").getJSONArray("candles");
   if(candles.length()==0)throw new IOException("No market candles");
   JSONObject last=candles.getJSONObject(candles.length()-1);
   double close=last.optDouble("close",Double.NaN);
   if(!Double.isFinite(close)||close<=0)throw new IOException("Invalid close price");
   String text="BTC / USD     "+String.format(Locale.ROOT,"%,.2f",close)+"     READ-ONLY";
   runOnUiThread(()->{chartView.setCandles(candles);marketPrice.setText(chartView.candles.isEmpty()?"BTC / USD     veri bekleniyor     READ-ONLY":text);});
  }catch(Exception e){runOnUiThread(()->{marketPrice.setText("BTC / USD     veri bekleniyor     READ-ONLY");chartView.clear();});}}).start();}
 void quote(){String f=asset(from),tt=asset(to),a=amount.getText().toString().trim();if(!a.matches("[0-9]+(\\.[0-9]{1,12})?")){result.setText("Geçerli bir miktar gir.");return;}result.setText("Fiyat hesaplanıyor…");new Thread(()->{try{String path="/convert/quote?fromCurrency="+enc(f)+"&toCurrency="+enc(tt)+"&fromAmount="+enc(a);JSONObject j=get(path);JSONObject d=j.optJSONObject("data");String out=d==null?"Fiyat şu anda alınamadı.":("Tahmini alacağın miktar\n"+d.optString("toAmount",d.optString("estimatedAmount","—"))+" "+tt.toUpperCase(Locale.ROOT)+"\nİşlem oluşturulmadı.");runOnUiThread(()->result.setText(out));}catch(Exception e){runOnUiThread(()->result.setText("Fiyat servisi şu anda kullanılamıyor. İşlem oluşturulmadı."));}}).start();}
 JSONObject get(String p)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(BuildConfig.MARSX_FINANCE_API_BASE_URL+p).openConnection();c.setConnectTimeout(7000);c.setReadTimeout(7000);c.setRequestProperty("Accept","application/json");int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();String body=read(in);c.disconnect();if(code>=400)throw new IOException("HTTP "+code);return new JSONObject(body);}
 String read(InputStream in)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String l;while((l=r.readLine())!=null&&b.length()<8192)b.append(l);return b.toString();}
 String enc(String s)throws Exception{return URLEncoder.encode(s,"UTF-8");}String asset(Spinner s){return s.getSelectedItem().toString().split(" ")[0].toLowerCase(Locale.ROOT);}
 Spinner spin(String[] a,int i){Spinner s=new Spinner(this);ArrayAdapter<String>d=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a){public View getView(int p,View v,android.view.ViewGroup g){TextView x=(TextView)super.getView(p,v,g);x.setTextColor(Color.WHITE);x.setTextSize(17);x.setPadding(18,18,18,18);x.setBackgroundColor(CARD);return x;}};s.setAdapter(d);s.setSelection(i);return s;}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(22,20,22,22);c.setBackground(round(CARD,22));return c;}LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
 TextView t(String x,int z,int col){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);v.setTextColor(col);v.setPadding(0,8,0,8);return v;}void oneLine(TextView v){v.setSingleLine(true);v.setEllipsize(android.text.TextUtils.TruncateAt.END);}void title(String x,int z){TextView v=t(x,z,Color.WHITE);v.setTypeface(null,Typeface.BOLD);root.addView(v);}void muted(String x){root.addView(t(x,14,MUTED));}
 LinearLayout.LayoutParams mp(int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=top;return p;}GradientDrawable round(int col,int rad){GradientDrawable g=new GradientDrawable();g.setColor(col);g.setCornerRadius(rad);return g;}GradientDrawable pill(int col,int stroke){GradientDrawable g=round(col,999);g.setStroke(1,stroke);return g;}GradientDrawable panel(int col,int rad,int stroke){GradientDrawable g=round(col,rad);g.setStroke(2,stroke);return g;}GradientDrawable box(){GradientDrawable g=round(Color.rgb(16,23,34),16);g.setStroke(1,Color.rgb(56,32,82));return g;}
 static final class ChartView extends View{
  Paint p=new Paint(1);ArrayList<float[]> candles=new ArrayList<>();int accent=Color.rgb(255,112,0);
  ChartView(android.content.Context c){super(c);setBackgroundColor(Color.rgb(7,12,19));}
  void clear(){candles.clear();setContentDescription("BTC USD mum grafiği; veri bekleniyor");invalidate();}
  void setCandles(JSONArray a){
   ArrayList<float[]> verified=new ArrayList<>();
   try{
    int start=Math.max(0,a.length()-64);
    for(int i=start;i<a.length();i++){
     JSONObject x=a.getJSONObject(i);
     double o=x.optDouble("open",Double.NaN),hi=x.optDouble("high",Double.NaN),lo=x.optDouble("low",Double.NaN),cl=x.optDouble("close",Double.NaN),v=x.optDouble("volume",0);
     if(!Double.isFinite(o)||!Double.isFinite(hi)||!Double.isFinite(lo)||!Double.isFinite(cl)||!Double.isFinite(v)
       ||o<=0||cl<=0||hi<Math.max(o,cl)||lo>Math.min(o,cl)||lo<=0||v<0)continue;
     verified.add(new float[]{(float)o,(float)hi,(float)lo,(float)cl,(float)v});
    }
   }catch(Exception ignored){verified.clear();}
   candles.clear();candles.addAll(verified);
   setContentDescription(candles.isEmpty()?"BTC USD mum grafiği; veri bekleniyor":"BTC USD doğrulanmış mum grafiği; salt okunur");
   invalidate();
  }
  protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight(),top=18,chartH=(int)(h*.72),volTop=top+chartH+18,volH=h-volTop-18;p.setStrokeWidth(1);p.setColor(Color.rgb(30,40,50));for(int i=0;i<=4;i++)c.drawLine(0,top+chartH*i/4f,w,top+chartH*i/4f,p);if(candles.isEmpty()){p.setStyle(Paint.Style.FILL);p.setColor(Color.LTGRAY);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(30);c.drawText("VERİ BEKLENİYOR",w/2f,h/2f,p);p.setTextSize(20);c.drawText("Gerçek piyasa verisi bulunamadı",w/2f,h/2f+38,p);p.setTextAlign(Paint.Align.LEFT);return;}float hi=0,lo=Float.MAX_VALUE,mv=1;for(float[] x:candles){hi=Math.max(hi,x[1]);lo=Math.min(lo,x[2]);mv=Math.max(mv,x[4]);}float gap=Math.max(6,w/(float)Math.max(24,candles.size())),body=Math.max(3,gap*.55f);Path sma=new Path();for(int i=0;i<candles.size();i++){float[] x=candles.get(i);float cx=i*gap+gap*.7f,yo=y(x[0],hi,lo,top,chartH),yh=y(x[1],hi,lo,top,chartH),yl=y(x[2],hi,lo,top,chartH),yc=y(x[3],hi,lo,top,chartH);boolean up=x[3]>=x[0];p.setColor(up?Color.rgb(22,199,132):Color.rgb(234,57,67));p.setStrokeWidth(2);c.drawLine(cx,yh,cx,yl,p);p.setStyle(Paint.Style.FILL);c.drawRoundRect(cx-body/2,Math.min(yo,yc),cx+body/2,Math.max(yo,yc)+1,3,3,p);p.setColor(Color.argb(130,180,190,205));c.drawRect(cx-body/2,volTop+volH*(1-x[4]/mv),cx+body/2,volTop+volH,p);if(i>=7){float s=0;for(int k=i-7;k<=i;k++)s+=candles.get(k)[3];float sy=y(s/8,hi,lo,top,chartH);if(i==7)sma.moveTo(cx,sy);else sma.lineTo(cx,sy);}}p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(accent);c.drawPath(sma,p);p.setStyle(Paint.Style.FILL);p.setTextSize(24);p.setColor(Color.LTGRAY);c.drawText("SMA 8",18,chartH+top-14,p);c.drawText("VOL",18,h-18,p);}
  float y(float v,float hi,float lo,int top,int chartH){return top+(hi-v)/Math.max(1,hi-lo)*chartH;}
 }
}
