package com.marsx.pool;

import android.app.*;import android.os.*;import android.content.*;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;

public class PremiumActivity extends Activity{
 static final int BG=Color.rgb(4,5,7),CARD=Color.rgb(15,17,21),ORANGE=Color.rgb(255,112,8),WHITE=Color.rgb(246,246,248),MUTED=Color.rgb(145,149,158),GREEN=Color.rgb(34,210,104),RED=Color.rgb(245,66,83);
 LinearLayout page,nav; TextView state,power,workers,shares,temp,battery,balance,network,elapsed; Button start; boolean running=false; long started; Handler timer=new Handler(Looper.getMainLooper()); Runnable tick=new Runnable(){public void run(){if(running&&elapsed!=null){long d=Math.max(0,System.currentTimeMillis()-started)/1000;elapsed.setText(String.format(Locale.ROOT,"%02d:%02d:%02d",d/3600,(d/60)%60,d%60));}timer.postDelayed(this,1000);}}; ExecutorService io=Executors.newSingleThreadExecutor(); LuckPoolClient pool=new LuckPoolClient(); SharedPreferences appPrefs,poolPrefs;
 @Override public void onCreate(Bundle b){super.onCreate(b);appPrefs=getSharedPreferences("marsx_premium",MODE_PRIVATE);poolPrefs=getSharedPreferences("vrsc_watch",MODE_PRIVATE);running=appPrefs.getBoolean("session_active",false);started=appPrefs.getLong("session_started",0);if(appPrefs.getBoolean("consent_ok",false))shell();else showSplash();}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(0,dp(7),0,dp(7));return v;}
 GradientDrawable shape(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp((int)r));g.setStroke(dp(1),Color.rgb(66,42,25));return g;}
 LinearLayout base(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setBackgroundColor(BG);return l;}
 LinearLayout card(){LinearLayout c=base();c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(shape(CARD,22));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(10));c.setLayoutParams(p);return c;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.BLACK);b.setTextSize(16);b.setAllCaps(false);b.setBackgroundTintList(ColorStateList.valueOf(ORANGE));return b;}
 TextView logo(){TextView x=t("MARS-X",29,WHITE);x.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);x.setLetterSpacing(.08f);return x;}
 void showSplash(){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);LinearLayout r=base();r.setGravity(Gravity.CENTER_HORIZONTAL);r.setPadding(dp(24),dp(22),dp(24),dp(24));sv.addView(r);r.addView(new EmblemView(this),new LinearLayout.LayoutParams(-1,dp(190)));TextView l=logo();l.setTextSize(40);l.setGravity(Gravity.CENTER);r.addView(l);TextView q=t("GELECEĞİ BUGÜNDEN KAZAN",14,ORANGE);q.setGravity(Gravity.CENTER);r.addView(q);r.addView(t("Premium Pool Controller",13,MUTED));Button bt=btn("HEMEN BAŞLA");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,dp(24),0,dp(12));r.addView(bt,p);bt.setOnClickListener(v->consent());setContentView(sv);}
 void consent(){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);LinearLayout r=base();r.setPadding(dp(24),dp(24),dp(24),dp(24));sv.addView(r);r.addView(logo());r.addView(t("MARS-X'e Hoş Geldin",27,ORANGE));String[] rows={"◉  Kolay Başla\n     Tek dokunuşla oturumu yönet","◉  Gerçek İstatistik\n     Doğrulanmış havuz verileri","◉  %3 Davet Kazancı\n     Arkadaşlarını davet et","◉  Güvenli ve Şeffaf\n     Kontrol her zaman sende"};for(String s:rows)r.addView(t(s,16,WHITE));CheckBox ok=new CheckBox(this);ok.setText("Koşulları ve gizlilik bildirimini kabul ediyorum");ok.setTextColor(MUTED);r.addView(ok);Button b=btn("KABUL ET VE DEVAM ET");r.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));b.setOnClickListener(v->{if(ok.isChecked()){appPrefs.edit().putBoolean("consent_ok",true).apply();shell();}else Toast.makeText(this,"Onay gerekli.",Toast.LENGTH_SHORT).show();});setContentView(sv);}
 void shell(){LinearLayout root=base();ScrollView s=new ScrollView(this);page=base();page.setPadding(dp(18),dp(16),dp(18),dp(20));s.addView(page);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setBackgroundColor(Color.rgb(9,10,13));addNav("⌂\nAna Sayfa",0);addNav("⌁\nKazanç",1);addNav("▣\nCüzdan",2);addNav("♧\nDavet",3);addNav("⚙\nAyarlar",4);root.addView(nav);setContentView(root);home();}
 void addNav(String s,int n){Button b=new Button(this);b.setText(s);b.setTextSize(10);b.setTextColor(MUTED);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);nav.addView(b,new LinearLayout.LayoutParams(0,dp(62),1));b.setOnClickListener(v->{if(n==0)home();if(n==1)earn();if(n==2)wallet();if(n==3)invite();if(n==4)settings();});}
 void head(String s){page.removeAllViews();LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(logo(),new LinearLayout.LayoutParams(0,-2,1));h.addView(t("●",18,ORANGE));page.addView(h);page.addView(t(s,14,ORANGE));}
 void home(){head("POOL BETA");LinearLayout b=card();b.addView(t("MEVCUT KAZANÇ",12,MUTED));balance=t("0.000000 MARS-X",31,WHITE);b.addView(balance);b.addView(t("Sağlayıcı doğrulaması ile güncellenir",12,GREEN));page.addView(b);LinearLayout c=card();state=t(running?"● OTURUM AKTİF":"● HAZIR",15,running?GREEN:MUTED);c.addView(state);c.addView(new MarsView(this),new LinearLayout.LayoutParams(-1,dp(250)));elapsed=t(running?"00:00:00":"--:--:--",24,WHITE);elapsed.setGravity(Gravity.CENTER);c.addView(elapsed);start=btn(running?"DURDUR":"BAŞLAT");c.addView(start,new LinearLayout.LayoutParams(-1,dp(58)));start.setOnClickListener(v->toggle());page.addView(c);statsCard();refreshDevice();refreshPool();timer.removeCallbacks(tick);timer.post(tick);}
 void statsCard(){LinearLayout s=card();s.addView(t("GÜÇ VE PERFORMANS",18,WHITE));LinearLayout row=new LinearLayout(this);power=metric(row,"Güç","— Sol/s");workers=metric(row,"Aktif Worker","—");s.addView(row);LinearLayout row2=new LinearLayout(this);shares=metric(row2,"Paylaşılan İş","—");temp=metric(row2,"Sıcaklık","43°C sınır");s.addView(row2);battery=t("Pil alt limiti %15  •  Cihaz pili —",13,MUTED);s.addView(battery);network=t("Ağ durumu  •  Veri bekleniyor",13,MUTED);s.addView(network);Button p=btn("CİHAZ / HAVUZ DURUMU");p.setOnClickListener(v->powerPage());s.addView(p);Button g=btn("GELİŞMİŞ GRAFİKLER");g.setOnClickListener(v->graphs());s.addView(g);page.addView(s);}
 TextView metric(LinearLayout r,String a,String b){LinearLayout c=base();c.setPadding(dp(10),dp(8),dp(10),dp(8));c.setBackground(shape(Color.rgb(20,22,27),14));c.addView(t(a,11,MUTED));TextView v=t(b,17,WHITE);c.addView(v);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(75),1);p.setMargins(dp(3),dp(3),dp(3),dp(3));r.addView(c,p);return v;}
 void toggle(){running=!running;if(running){started=System.currentTimeMillis();refreshPool();}else pool.cancel();appPrefs.edit().putBoolean("session_active",running).putLong("session_started",started).apply();state.setText(running?"● OTURUM AKTİF":"● DURDURULDU");state.setTextColor(running?GREEN:MUTED);start.setText(running?"DURDUR":"BAŞLAT");}
 void earn(){head("KAZANÇ İSTATİSTİKLERİ");LinearLayout c=card();c.addView(t("Günlük     Haftalık     Aylık     Tümü",14,ORANGE));c.addView(t("0.000000 MARS-X",31,WHITE));c.addView(new ChartView(this),new LinearLayout.LayoutParams(-1,dp(210)));page.addView(c);LinearLayout r=new LinearLayout(this);metric(r,"Ortalama/Saat","—");metric(r,"En Yüksek","—");page.addView(r);LinearLayout r2=new LinearLayout(this);metric(r2,"Toplam Süre","—");metric(r2,"Aktif Oturum",running?"Aktif":"Kapalı");page.addView(r2);history();}
 void graphs(){head("GRAFİKLER");LinearLayout c=card();c.addView(t("Kazanç     Cihaz     Ağ     Sıcaklık",14,ORANGE));c.addView(new MultiChartView(this),new LinearLayout.LayoutParams(-1,dp(235)));c.addView(t("Günlük  •  Haftalık  •  Aylık",12,MUTED));c.addView(t("Doğrulanmış veri geldikçe çizgiler gerçek örneklerle güncellenir.",13,MUTED));page.addView(c);LinearLayout d=card();d.addView(t("HAFTALIK KAZANÇ DAĞILIMI",17,WHITE));d.addView(new BarView(this),new LinearLayout.LayoutParams(-1,dp(190)));d.addView(t("Pzt   Sal   Çar   Per   Cum   Cmt   Paz",12,MUTED));page.addView(d);}
 void history(){LinearLayout h=card();h.addView(t("İŞLEM GEÇMİŞİ",18,WHITE));h.addView(t("Henüz doğrulanmış işlem yok",14,MUTED));page.addView(h);}
 void wallet(){head("CÜZDAN");LinearLayout c=card();c.addView(t("TOPLAM BAKİYE",12,MUTED));c.addView(t("0.000000 MARS-X",32,WHITE));c.addView(t("Beta içi doğrulanmış kazanç",12,ORANGE));page.addView(c);LinearLayout a=new LinearLayout(this);metric(a,"Gönder","Yakında");metric(a,"Çekim","Kapalı");metric(a,"Dönüştür","Kapalı");page.addView(a);page.addView(t("Gerçek çekim ve dönüşüm güvenlik kapıları açılana kadar devre dışıdır.",12,MUTED));history();}
 void invite(){head("DAVET ET KAZAN");LinearLayout c=card();TextView i=t("● ● ●",44,ORANGE);i.setGravity(Gravity.CENTER);c.addView(i);TextView x=t("Arkadaşlarını Davet Et",22,WHITE);x.setGravity(Gravity.CENTER);c.addView(x);TextView p=t("Her uygun davet için\n+%3 kazanç bonusu",24,ORANGE);p.setGravity(Gravity.CENTER);c.addView(p);c.addView(t("Davet bağlantın",12,MUTED));TextView link=t("MARS-X Pool Beta",14,WHITE);link.setBackground(shape(Color.rgb(20,22,27),12));link.setPadding(dp(12),dp(10),dp(12),dp(10));c.addView(link);Button b=btn("WHATSAPP / TELEGRAM / PAYLAŞ");b.setOnClickListener(v->{Intent in=new Intent(Intent.ACTION_SEND);in.setType("text/plain");in.putExtra(Intent.EXTRA_TEXT,"MARS-X Pool Beta");startActivity(Intent.createChooser(in,"Paylaş"));});c.addView(b);c.addView(t("Toplam davet: —\nDavet kazancı: —",14,MUTED));page.addView(c);}
 void settings(){head("AYARLAR");LinearLayout c=card();Switch auto=new Switch(this);auto.setText("Başlangıçta Otomatik Oturum");auto.setTextColor(WHITE);auto.setChecked(appPrefs.getBoolean("auto_start",false));auto.setOnCheckedChangeListener((b,v)->appPrefs.edit().putBoolean("auto_start",v).apply());c.addView(auto);Switch notices=new Switch(this);notices.setText("Bildirimler");notices.setTextColor(WHITE);notices.setChecked(appPrefs.getBoolean("notices",true));notices.setOnCheckedChangeListener((b,v)->appPrefs.edit().putBoolean("notices",v).apply());c.addView(notices);setting(c,"Hesap Bilgileri",()->info("HESAP","Google hesap ve doğrulanmış profil bağlantısı ana hesap servisiyle yönetilir."));setting(c,"Bildirimler",this::notifications);setting(c,"Tema  •  Mars Turuncu",()->{});setting(c,"Dil  •  Türkçe",()->{});setting(c,"Güç ve Performans",this::powerPage);setting(c,"Pil Alt Limiti  •  %15",this::batterySettings);setting(c,"Sıcaklık Limiti  •  43°C",this::thermalSettings);setting(c,"Güvenlik",()->info("GÜVENLİK","Gerçek bakiye yalnızca doğrulanmış sağlayıcı uzlaştırmasından oluşur."));setting(c,"Hakkında  •  v1.0.0",this::about);page.addView(c);}
void batterySettings(){head("PİL OPTİMİZASYONU");LinearLayout c=card();c.addView(t("Alt limit",16,WHITE));SeekBar b=new SeekBar(this);b.setMax(40);b.setProgress(appPrefs.getInt("battery_limit",15));TextView v=t(b.getProgress()+"%",24,ORANGE);b.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar x,int n,boolean u){n=Math.max(5,n);v.setText(n+"%");appPrefs.edit().putInt("battery_limit",n).apply();}public void onStartTrackingTouch(SeekBar x){}public void onStopTrackingTouch(SeekBar x){}});c.addView(v);c.addView(b);c.addView(t("Bu eşik koruma/uyarı ayarıdır; cihazda gizli mining başlatmaz.",12,MUTED));page.addView(c);}
 void thermalSettings(){head("SICAKLIK KONTROLÜ");LinearLayout c=card();c.addView(t("Sıcaklık uyarı sınırı",16,WHITE));SeekBar b=new SeekBar(this);b.setMax(15);int cur=appPrefs.getInt("thermal_limit",43);b.setProgress(cur-35);TextView v=t(cur+"°C",24,ORANGE);b.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar x,int n,boolean u){int z=35+n;v.setText(z+"°C");appPrefs.edit().putInt("thermal_limit",z).apply();}public void onStartTrackingTouch(SeekBar x){}public void onStopTrackingTouch(SeekBar x){}});c.addView(v);c.addView(b);page.addView(c);}
void setting(LinearLayout c,String label,Runnable a){Button b=new Button(this);b.setText(label+"   ›");b.setTextColor(WHITE);b.setTextSize(15);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(v->a.run());c.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));}
 void info(String title,String body){head(title);LinearLayout c=card();c.addView(t(body,15,MUTED));page.addView(c);}
 void notifications(){head("BİLDİRİMLER");LinearLayout c=card();c.addView(t("Sistem mesajları",18,WHITE));c.addView(t("Yeni doğrulanmış kazanç, oturum ve güvenlik bildirimleri burada gösterilir.",14,MUTED));c.addView(t("Şu anda yeni bildirim yok",14,GREEN));page.addView(c);}
 void about(){head("HAKKINDA");LinearLayout c=card();c.addView(new EmblemView(this),new LinearLayout.LayoutParams(-1,dp(190)));TextView l=logo();l.setGravity(Gravity.CENTER);c.addView(l);c.addView(t("MARS-X Pool Beta • v1.0.0\nİzinli havuz/controller arayüzü. Cihaz üzerinde gizli madencilik yapılmaz.",14,MUTED));page.addView(c);}
 void powerPage(){head("GÜÇ VE PERFORMANS");LinearLayout c=card();c.addView(new GaugeView(this),new LinearLayout.LayoutParams(-1,dp(230)));LinearLayout r=new LinearLayout(this);power=metric(r,"Doğrulanmış Güç","— Sol/s");workers=metric(r,"Aktif Worker","—");c.addView(r);LinearLayout q=new LinearLayout(this);shares=metric(q,"Paylaşılan İş","—");network=metric(q,"Ağ","Bekleniyor");c.addView(q);c.addView(t("Geçerli / geçersiz pay ve ağ ayrıntıları yalnız sağlayıcı tarafından doğrulandığında gösterilir.",12,MUTED));Button adv=btn("GELİŞMİŞ AYARLAR");adv.setOnClickListener(v->settings());c.addView(adv);page.addView(c);refreshDevice();refreshPool();}
 void refreshDevice(){Intent i=registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));if(i==null)return;int level=i.getIntExtra(android.os.BatteryManager.EXTRA_LEVEL,-1),scale=i.getIntExtra(android.os.BatteryManager.EXTRA_SCALE,100),raw=i.getIntExtra(android.os.BatteryManager.EXTRA_TEMPERATURE,-1);int pct=scale>0?Math.round(level*100f/scale):-1;float tc=raw>=0?raw/10f:-1;if(battery!=null)battery.setText("Pil alt limiti %15  •  Cihaz pili "+(pct<0?"—":pct+"%"));int lim=appPrefs.getInt("thermal_limit",43);if(temp!=null)temp.setText(tc<0?lim+"°C sınır":String.format(Locale.getDefault(),"%.1f°C / %d°C",tc,lim));}
 void refreshPool(){final String addr=poolPrefs.getString("address","");if(!VrscAddress.valid(addr)){if(network!=null)network.setText("Havuz verisi • Adres yapılandırılmadı");return;}if(network!=null)network.setText("Havuz verisi • Güncelleniyor…");final long t0=System.currentTimeMillis();io.submit(()->{try{LuckPoolClient.Snapshot x=pool.load(addr);long ms=System.currentTimeMillis()-t0;runOnUiThread(()->{if(power!=null)power.setText(String.format(Locale.getDefault(),"%,.2f Sol/s",x.hashrate));if(workers!=null){int n=0;for(LuckPoolClient.Worker w:x.workers)if(w.online)n++;workers.setText(String.valueOf(n));}if(shares!=null)shares.setText(x.shareValue);if(network!=null)network.setText("Sağlayıcı bağlantısı • "+ms+" ms");});}catch(Exception e){runOnUiThread(()->{if(network!=null)network.setText("Havuz verisi • Kullanılamıyor");});}});}
 public static class EmblemView extends View{Paint p=new Paint(1);public EmblemView(Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.setStyle(Paint.Style.FILL);p.setColor(ORANGE);Path m=new Path();m.moveTo(w*.15f,h*.82f);m.lineTo(w*.30f,h*.18f);m.lineTo(w*.50f,h*.57f);m.lineTo(w*.70f,h*.18f);m.lineTo(w*.85f,h*.82f);m.lineTo(w*.68f,h*.82f);m.lineTo(w*.63f,h*.50f);m.lineTo(w*.50f,h*.78f);m.lineTo(w*.37f,h*.50f);m.lineTo(w*.32f,h*.82f);m.close();c.drawPath(m,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(4,w*.018f));RectF r=new RectF(w*.10f,h*.32f,w*.90f,h*.70f);c.save();c.rotate(-14,w/2,h/2);c.drawOval(r,p);c.restore();}} public static class GaugeView extends View{Paint p=new Paint(1);public GaugeView(Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),cx=w/2,cy=h*.62f,r=Math.min(w,h)*.38f;p.setStyle(Paint.Style.STROKE);p.setStrokeCap(Paint.Cap.ROUND);p.setStrokeWidth(Math.max(16,w*.055f));p.setColor(Color.rgb(55,31,18));RectF a=new RectF(cx-r,cy-r,cx+r,cy+r);c.drawArc(a,150,240,false,p);p.setColor(ORANGE);c.drawArc(a,150,120,false,p);p.setStyle(Paint.Style.FILL);p.setColor(WHITE);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(w*.11f);c.drawText("⚡",cx,cy,p);p.setTextSize(w*.05f);p.setColor(MUTED);c.drawText("DOĞRULANMIŞ GÜÇ",cx,cy+h*.15f,p);}} public static class MarsView extends View{Paint p=new Paint(1);public MarsView(Context c){super(c);}protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),cx=w/2,cy=h*.48f,r=Math.min(w,h)*.31f;p.setStyle(Paint.Style.FILL);p.setShader(new RadialGradient(cx-r*.3f,cy-r*.35f,r*1.4f,new int[]{Color.rgb(255,151,55),Color.rgb(181,54,12),Color.rgb(40,8,5)},null,Shader.TileMode.CLAMP));c.drawCircle(cx,cy,r,p);p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(5,w*.018f));p.setColor(ORANGE);RectF o=new RectF(cx-r*1.35f,cy-r*.45f,cx+r*1.35f,cy+r*.45f);c.save();c.rotate(-18,cx,cy);c.drawOval(o,p);c.restore();p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(90,0,0,0));c.drawCircle(cx+r*.28f,cy-r*.16f,r*.13f,p);c.drawCircle(cx-r*.25f,cy+r*.2f,r*.09f,p);}}
 public static class ChartView extends View{Paint p=new Paint(1);public ChartView(Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.setStrokeWidth(1);p.setColor(Color.rgb(36,40,45));for(int i=1;i<5;i++)c.drawLine(0,h*i/5,w,h*i/5,p);p.setColor(ORANGE);p.setStrokeWidth(5);Path q=new Path();q.moveTo(0,h*.75f);for(int i=1;i<=12;i++){float x=w*i/12f;float y=h*(.72f-(i%4)*.025f);q.lineTo(x,y);}c.drawPath(q,p);p.setColor(Color.argb(35,255,112,8));q.lineTo(w,h);q.lineTo(0,h);q.close();c.drawPath(q,p);}}
 public static class MultiChartView extends View{Paint p=new Paint(1);public MultiChartView(Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),top=h*.12f,bottom=h*.84f;p.setStrokeWidth(1);p.setColor(Color.rgb(38,41,46));for(int i=0;i<5;i++){float y=top+(bottom-top)*i/4;c.drawLine(0,y,w,y,p);}for(int i=0;i<7;i++){float x=w*i/6;c.drawLine(x,top,x,bottom,p);}int[] cs={Color.rgb(30,144,255),Color.rgb(255,55,90),ORANGE};for(int k=0;k<3;k++){p.setColor(cs[k]);p.setStrokeWidth(4);p.setStyle(Paint.Style.STROKE);Path q=new Path();for(int i=0;i<7;i++){float x=w*i/6f;float base=.72f-k*.08f;float y=h*(base-(i%4)*(.035f+k*.008f));if(i==0)q.moveTo(x,y);else q.lineTo(x,y);}c.drawPath(q,p);p.setStyle(Paint.Style.FILL);for(int i=0;i<7;i++){float x=w*i/6f;float base=.72f-k*.08f;float y=h*(base-(i%4)*(.035f+k*.008f));c.drawCircle(x,y,5,p);}}p.setTextSize(w*.035f);p.setColor(MUTED);p.setTextAlign(Paint.Align.LEFT);c.drawText("Veri bekleniyor",8,h*.97f,p);}}
 public static class BarView extends View{Paint p=new Paint(1);public BarView(Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.setColor(ORANGE);for(int i=0;i<7;i++){float bw=w/12f,x=w*(i+1)/8f;float bh=h*(.15f+.04f*(i%3));c.drawRoundRect(x-bw/2,h-bh,x+bw/2,h,8,8,p);}}}
 @Override protected void onDestroy(){pool.cancel();io.shutdownNow();timer.removeCallbacksAndMessages(null);super.onDestroy();}
}