import os from "node:os";import crypto from "node:crypto";import {spawn} from "node:child_process";import {parseMinerLine} from "./miner-log-parser.mjs";
const API=process.env.MARSX_API_BASE_URL||"";const LICENSE=process.env.MARSX_LICENSE||"";const INSTALL=process.env.MARSX_INSTALL_ID||"";const POOL=process.env.MARSX_POOL_URL||"";const USER=process.env.MARSX_MINER_USER||"";const BIN=process.env.MARSX_MINER_BIN||"";const EXPECTED=(process.env.MARSX_MINER_SHA256||"").toLowerCase();const BASE_THREADS=Math.max(1,Number(process.env.MARSX_THREADS)||os.cpus().length);let desiredCpu=50;function threads(){return Math.max(1,Math.min(BASE_THREADS,Math.round(BASE_THREADS*desiredCpu/100)))}const WORKER=(process.env.MARSX_WORKER_ID||("node-"+crypto.createHash("sha256").update(os.hostname()).digest("hex").slice(0,12))).replace(/[^A-Za-z0-9_-]/g,"-");
let miner=null,rate=0,state="stopped",lastSeq=0,accepted=0,rejected=0,poolConnected=false,lastShareAt=0;
function deviceClass(){if(process.env.MARSX_DEVICE_CLASS)return process.env.MARSX_DEVICE_CLASS;return os.platform()==="linux"&&/arm|aarch/i.test(os.arch())?"sbc":"desktop"}
function caps(){return ["cpu-mining","process-supervision","hashrate-telemetry","power-control"]}
async function sha(path){const fs=await import("node:fs");return new Promise((ok,no)=>{const h=crypto.createHash("sha256"),s=fs.createReadStream(path);s.on("data",x=>h.update(x));s.on("error",no);s.on("end",()=>ok(h.digest("hex")))})}
async function verified(){if(!BIN||!/^[a-f0-9]{64}$/.test(EXPECTED))return false;try{return await sha(BIN)===EXPECTED}catch{return false}}
function parse(line){const p=parseMinerLine(line);if(p.hashrate>=0)rate=p.hashrate;if(p.poolConnected)poolConnected=true;if(p.accepted){accepted++;lastShareAt=Date.now()}else if(p.rejected){rejected++;lastShareAt=Date.now()}}
async function start(){if(miner||!POOL.startsWith("stratum+tcp://")||!USER||!(await verified()))return false;const child=spawn(BIN,["-a","verus","-o",POOL,"-u",USER,"-p","x","-t",String(threads())],{stdio:["ignore","pipe","pipe"]});const started=await new Promise(ok=>{let done=false;const finish=v=>{if(!done){done=true;ok(v)}};child.once("spawn",()=>finish(true));child.once("error",()=>finish(false))});if(!started){try{child.kill()}catch{}return false}miner=child;state="running";child.stdout.on("data",b=>String(b).split(/\r?\n/).forEach(parse));child.stderr.on("data",b=>String(b).split(/\r?\n/).forEach(parse));child.on("error",()=>{if(miner===child){miner=null;rate=0;poolConnected=false;state="error"}});child.on("exit",()=>{if(miner===child){miner=null;rate=0;poolConnected=false;state="stopped"}});return true}
async function stop(){const p=miner;if(p){p.kill("SIGTERM");await Promise.race([new Promise(ok=>p.once("exit",ok)),new Promise(ok=>setTimeout(ok,3000))]);if(miner===p){try{p.kill("SIGKILL")}catch{}miner=null}}rate=0;poolConnected=false;state="stopped"}
async function post(path,body){if(!API||!LICENSE||!INSTALL)return null;try{const r=await fetch(API+path,{method:"POST",headers:{"content-type":"application/json","authorization":"License "+LICENSE,"x-install-id":INSTALL},body:JSON.stringify(body),signal:AbortSignal.timeout(10000)});return r.ok?await r.json().catch(()=>({})):null}catch{return null}}
let heartbeatBusy=false;async function heartbeat(){if(heartbeatBusy)return;heartbeatBusy=true;try{const j=await post("/heartbeat",{node_id:WORKER,install_id:INSTALL,label:os.hostname(),platform:os.platform(),arch:os.arch(),device_class:deviceClass(),capabilities:caps(),cpu_percent:null,miner_state:state,hashrate_sols:rate,pool_connected:poolConnected,accepted_shares:accepted,rejected_shares:rejected,last_share_at:lastShareAt||null});const cmd=j?.command;if(cmd&&Number(cmd.seq)>lastSeq){const seq=Number(cmd.seq),nextCpu=Math.max(10,Math.min(100,Number(cmd.cpuPercent)||50)),powerChanged=nextCpu!==desiredCpu;desiredCpu=nextCpu;let applied=true;if(powerChanged&&miner){await stop();if(cmd.minerState==="running")applied=await start();}else if(cmd.minerState==="running")applied=miner?true:await start();else if(cmd.minerState==="stopped")await stop();if(applied)lastSeq=seq;}}finally{heartbeatBusy=false}}
async function shutdown(){await stop();process.exit(0)}process.on("SIGINT",shutdown);process.on("SIGTERM",shutdown);
await post("/register",{node_id:WORKER,install_id:INSTALL,label:os.hostname(),platform:os.platform(),arch:os.arch(),device_class:deviceClass(),capabilities:caps()});if(process.env.MARSX_AUTOSTART==="1")await start();await heartbeat();setInterval(heartbeat,30000);
console.log(JSON.stringify({workerId:WORKER,platform:os.platform(),arch:os.arch(),deviceClass:deviceClass(),minerVerified:await verified(),state}));
