import os from "node:os";import crypto from "node:crypto";import {spawn} from "node:child_process";
const API=process.env.MARSX_API_BASE_URL||"";const LICENSE=process.env.MARSX_LICENSE||"";const INSTALL=process.env.MARSX_INSTALL_ID||"";const POOL=process.env.MARSX_POOL_URL||"";const USER=process.env.MARSX_MINER_USER||"";const BIN=process.env.MARSX_MINER_BIN||"";const EXPECTED=(process.env.MARSX_MINER_SHA256||"").toLowerCase();const BASE_THREADS=Math.max(1,Number(process.env.MARSX_THREADS)||os.cpus().length);let desiredCpu=50;function threads(){return Math.max(1,Math.min(BASE_THREADS,Math.round(BASE_THREADS*desiredCpu/100)))}const WORKER=(process.env.MARSX_WORKER_ID||("node-"+crypto.createHash("sha256").update(os.hostname()).digest("hex").slice(0,12))).replace(/[^A-Za-z0-9_-]/g,"-");
let miner=null,rate=0,state="stopped",lastSeq=0;
function deviceClass(){if(process.env.MARSX_DEVICE_CLASS)return process.env.MARSX_DEVICE_CLASS;return os.platform()==="linux"&&/arm|aarch/i.test(os.arch())?"sbc":"desktop"}
function caps(){return ["cpu-mining","process-supervision","hashrate-telemetry"]}
async function sha(path){const fs=await import("node:fs");return new Promise((ok,no)=>{const h=crypto.createHash("sha256"),s=fs.createReadStream(path);s.on("data",x=>h.update(x));s.on("error",no);s.on("end",()=>ok(h.digest("hex")))})}
async function verified(){if(!BIN||!/^[a-f0-9]{64}$/.test(EXPECTED))return false;try{return await sha(BIN)===EXPECTED}catch{return false}}
function parse(line){const m=line.match(/([0-9]+(?:\.[0-9]+)?)\s*([kmg]?)h?\/?s/i);if(!m)return;let v=Number(m[1]);if(/k/i.test(m[2]))v*=1e3;if(/m/i.test(m[2]))v*=1e6;if(/g/i.test(m[2]))v*=1e9;rate=v}
async function start(){if(miner||!POOL.startsWith("stratum+tcp://")||!USER||!(await verified()))return false;miner=spawn(BIN,["-a","verus","-o",POOL,"-u",USER,"-p","x","-t",String(threads())],{stdio:["ignore","pipe","pipe"]});state="running";miner.stdout.on("data",b=>String(b).split(/\r?\n/).forEach(parse));miner.stderr.on("data",b=>String(b).split(/\r?\n/).forEach(parse));miner.on("exit",()=>{miner=null;rate=0;state="stopped"});return true}
function stop(){if(miner){miner.kill("SIGTERM");miner=null}rate=0;state="stopped"}
async function post(path,body){if(!API||!LICENSE||!INSTALL)return null;const r=await fetch(API+path,{method:"POST",headers:{"content-type":"application/json","authorization":"Bearer "+LICENSE,"x-install-id":INSTALL},body:JSON.stringify(body)});return r.ok?await r.json().catch(()=>({})):null}
async function heartbeat(){const j=await post("/heartbeat",{node_id:WORKER,install_id:INSTALL,label:os.hostname(),platform:os.platform(),arch:os.arch(),device_class:deviceClass(),capabilities:caps(),cpu_percent:null,miner_state:state,hashrate_sols:rate});const cmd=j?.command;if(cmd&&Number(cmd.seq)>lastSeq){lastSeq=Number(cmd.seq);const nextCpu=Math.max(10,Math.min(100,Number(cmd.cpuPercent)||50));const powerChanged=nextCpu!==desiredCpu;desiredCpu=nextCpu;if(powerChanged&&miner){stop();if(cmd.minerState==="running")await start();}else if(cmd.minerState==="running")await start();else if(cmd.minerState==="stopped")stop();}}
process.on("SIGINT",()=>{stop();process.exit(0)});process.on("SIGTERM",()=>{stop();process.exit(0)});
await post("/register",{node_id:WORKER,install_id:INSTALL,label:os.hostname(),platform:os.platform(),arch:os.arch(),device_class:deviceClass(),capabilities:caps()});if(process.env.MARSX_AUTOSTART==="1")await start();await heartbeat();setInterval(heartbeat,30000);
console.log(JSON.stringify({workerId:WORKER,platform:os.platform(),arch:os.arch(),deviceClass:deviceClass(),minerVerified:await verified(),state}));
