package com.marsx.worker;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.io.File;import java.security.*;import java.io.*;
public final class WorkerActivity extends Activity {
 static final int BG=Color.rgb(9,10,13), CARD=Color.rgb(20,21,25), ORANGE=Color.rgb(255,122,0), WHITE=Color.WHITE, MUTED=Color.rgb(160,164,174), GREEN=Color.rgb(71,211,142);
 TextView status, miner, safety; Handler ui=new Handler(Looper.getMainLooper()); Runnable refresh;
 public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},1001);render();refresh=()->{refreshState();ui.postDelayed(refresh,2000);};}\n protected void onResume(){super.onResume();if(refresh!=null){ui.removeCallbacks(refresh);ui.post(refresh);}}\n protected void onPause(){if(refresh!=null)ui.removeCallbacks(refresh);super.onPause();}
 void render(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(20),dp(30),dp(20),dp(30));r.setBackgroundColor(BG);
  TextView brand=txt("MARS-X",13,ORANGE);brand.setLetterSpacing(.18f);brand.setTypeface(Typeface.DEFAULT_BOLD);r.addView(brand);TextView title=txt("WORKER",30,WHITE);title.setTypeface(Typeface.DEFAULT_BOLD);r.addView(title);r.addView(txt("Bu bileşen yalnız sen Başlat dediğinde compute çalıştırır.",13,MUTED));
  LinearLayout state=card();state.addView(txt("WORKER DURUMU",11,ORANGE));status=txt("○  DURDURULDU",20,WHITE);status.setTypeface(Typeface.DEFAULT_BOLD);state.addView(status);miner=txt(minerReady()?"●  MINER DOĞRULANDI":"○  MINER KURULUMU BEKLENİYOR",13,minerReady()?GREEN:MUTED);state.addView(miner);safety=txt(safetyText(),13,MUTED);state.addView(safety);r.addView(state);
  LinearLayout limits=card();limits.addView(txt("GÜVENLİK",11,ORANGE));limits.addView(metric("Pil alt sınırı","15%"));limits.addView(metric("Termal üst sınır","43°C"));limits.addView(metric("Hashrate","Gerçek miner çıktısı"));r.addView(limits);
  Button start=btn("WORKER'I BAŞLAT",true);start.setOnClickListener(v->{if(!minerReady()){status.setText("○  MINER DOĞRULAMASI GEREKLİ");return;}Intent wi=new Intent(this,WorkerService.class).setAction("START");if(Build.VERSION.SDK_INT>=26)startForegroundService(wi);else startService(wi);status.setText("●  BAŞLATILIYOR…");status.setTextColor(GREEN);});r.addView(start);
  Button stop=btn("DURDUR",false);stop.setOnClickListener(v->{startService(new Intent(this,WorkerService.class).setAction("STOP"));status.setText("○  DURDURULDU");status.setTextColor(WHITE);});r.addView(stop);
  refreshState();TextView note=txt("Miner doğrulanmadan uygulama çalışan veya kazanç üreten worker göstermez. Pil ya da sıcaklık sınırı aşılırsa compute otomatik kesilir ve güvenli koşullar dönünce yalnız önceki Başlat isteği varsa devam eder.",12,MUTED);note.setPadding(0,dp(16),0,0);r.addView(note);sc.addView(r);setContentView(sc);}
 void refreshState(){if(status==null)return;SharedPreferences p=getSharedPreferences("worker",MODE_PRIVATE);String s=p.getString("service_state","stopped");double hr=Double.longBitsToDouble(p.getLong("hashrate_bits",Double.doubleToRawLongBits(0d)));String label;if("running".equals(s))label="●  ÇALIŞIYOR  •  "+formatHash(hr);else if("protected".equals(s))label="◌  KORUMA AKTİF";else if("waiting".equals(s))label="◌  YENİDEN BAŞLATMA BEKLENİYOR";else if("error".equals(s))label="!  WORKER HATASI";else label="○  DURDURULDU";status.setText(label);status.setTextColor("running".equals(s)?GREEN:("error".equals(s)?ORANGE:WHITE));if(miner!=null)miner.setText(minerReady()?"●  MINER DOĞRULANDI":"○  MINER KURULUMU BEKLENİYOR");if(safety!=null)safety.setText(safetyText());}\n String formatHash(double v){String u="H/s";if(v>=1e9){v/=1e9;u="GH/s";}else if(v>=1e6){v/=1e6;u="MH/s";}else if(v>=1e3){v/=1e3;u="kH/s";}return String.format(java.util.Locale.ROOT,v>=100?"%.0f %s":"%.1f %s",v,u);}\n boolean minerReady(){File f=new File(getFilesDir(),"miner/ccminer");String e=getSharedPreferences("worker",MODE_PRIVATE).getString("miner_sha256","");return f.isFile()&&f.canExecute()&&e.matches("[a-f0-9]{64}")&&e.equals(sha(f));}
 String safetyText(){BatteryManager b=getSystemService(BatteryManager.class);int p=b.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY);Intent x=registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));float t=x==null?0:x.getIntExtra(BatteryManager.EXTRA_TEMPERATURE,0)/10f;return "Pil "+p+"%  •  "+String.format(java.util.Locale.ROOT,"%.1f°C",t)+(p>=15&&t<43?"  •  HAZIR":"  •  KORUMA AKTİF");}
 String sha(File f){try{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(f)){byte[] b=new byte[8192];for(int n;(n=in.read(b))>0;)d.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte x:d.digest())s.append(String.format(java.util.Locale.ROOT,"%02x",x));return s.toString();}catch(Exception e){return "";}}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackgroundColor(CARD);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(16),0,0);c.setLayoutParams(p);return c;}
 LinearLayout metric(String a,String b){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);l.setMinimumHeight(dp(48));TextView x=txt(a,13,MUTED),y=txt(b,13,WHITE);l.addView(x,new LinearLayout.LayoutParams(0,-2,1));l.addView(y);return l;}
 TextView txt(String s,int z,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(5));return t;}
 Button btn(String s,boolean primary){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setMinHeight(dp(52));b.setTextColor(primary?BG:WHITE);if(primary)b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(ORANGE));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,dp(14),0,0);b.setLayoutParams(p);return b;}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}